### ISSUE TITLE
オッズが取得できていないレースがある

### ISSUE THREAD

**Issue by hxbdy** [hxbdy/HorseRacingAI#14]
# 発生した問題
該当レース
https://db.netkeiba.com/race/202106050509
DBから上記レースの1位オッズの取得に失敗した。

# 詳細
db_race_1st_odds(race_id = "202106050509") で
一位オッズの要求を行うと空データが返ってきた。

# 調査
ちなみにそのレースのオッズ全取得要求でも1件しか返ってこなかった。
想定では各馬のオッズが複数件返ってくるはず。

# 再現, 確認方法
sha : 440e9a062990f3a8eb1d91a01cfb383dd4b7ba59
>sqlite3 ./resrc/netkeibaDB/netkeiba.db
SQLite version 3.38.5 2022-05-06 15:25:27
Enter ".help" for usage hints.
sqlite> select odds from race_info where race_id="202106050509" and result="1";
(ここで何も返ってきていない)
sqlite> select odds from race_info where race_id="202106050509";               
146.2
sqlite> select odds from race_info where race_id="198608040411"; 
1.8
11.7
20.4
9.0
16.3
13.2

24.6
4.8
17.5
184.4
51.3
18.1
267.9
sqlite>

**Comment by double-log** [comment]
コード上のバグではなく、現在試験的に使用しているデータベース収集されない仕様であるために発生している。
現在試験的に使用しているデータベースは、2021年12月までの重賞レースまでのレースの結果データと、それらに出走した馬のデータが含まれる。
race_id=202106050509 は非重賞レースであり、「このレースに出走した」という条件では、馬のデータは収拾されない。今回、このrace_idでヒットしたレコードは、2021年12月までの重賞レースに出走していたためにスクレイプされた。
race_id=198608040411 はG2レースのため、これに出走した馬のデータは含まれている。

なお、オッズはレースのデータではなく、馬のデータとしてスクレイプされ保存されている。

**Comment by hxbdy** [comment]
重賞のレースのオッズは取っていないとのこと。  
odds は解析用でしか使っていないので、今のところ問題なし。  
クローズする。
