### ISSUE TITLE
racedbLearningListの内容は何を含むべきか？

### ISSUE THREAD

**Issue by double-log** [hxbdy/HorseRacingAI#6]
scrapingDataNrm.py内のracedbLearningListには，何を含めれば良いか？

現状，レースの入力と結果（タイム・着差）がともに入っている．
直接，学習データとして使うのであれば，レースの入力データのみにして，タイムと着差は別の変数にしたほうがよい？

**Comment by hxbdy** [comment]
学習時にフィードバックとして扱われる正解ラベルt行列は1つの想定です。
doc/20220625.md の案1より、今回正解ラベルtとして扱うのは順位で、
t = [1番の馬が1位になる確率, 2番の馬が1位になる確率, ... n番の馬が1位になる確率]
を与える。
ルールとして、以下を守る。
$$\sum_{k=1}^{n}  t_k = 1$$ 
値の決め方に「大差をつけて勝ったか、僅差か」を表現したいため、  
僅差の馬同士の正解ラベルの値は近い値に、大差の馬同士は離れた値にしたい。
$$t_1 \fallingdotseq t_2 > t_3 \gg t_4 > ...$$
現状表現されていないが、着差を使って正解ラベルtを作成したい。

**Comment by double-log** [comment]
正解ラベルtの作成について承知した．

学習データの作成において，[racedbLearningList, horsedbLearningList] を入力データとするように各LearningListを作成して，それとは別に正解ラベルtを作るのはどうだろうか．

**Comment by hxbdy** [comment]
賛成。tを作るための計算式は要相談かな。
